import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.6.4',
  date: '2021-11-18T00:54:39.207Z',
};
export default meta;
