import type MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.6.4',
  date: '2021-12-14T15:29:37.764Z',
};
export default meta;
