import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.6.2',
  date: '2021-08-30T13:13:26.497Z',
};
export default meta;
